-- Add migration script here

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "CodeSnippets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "line" int NOT NULL DEFAULT 0,
  "code" text NOT NULL
);

CREATE TABLE "Layers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "file_path" text NOT NULL,
  "code" text NOT NULL,
  "line_number" int NOT NULL DEFAULT 0,
  "column_number" int NOT NULL DEFAULT 0
);

CREATE TABLE "BacktracesLayers" (
  "backtrace_id" int PRIMARY KEY,
  "layer_id" int UNIQUE
);

CREATE TABLE "Backtraces" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE "Logs" (
  "id" uuid UNIQUE DEFAULT (uuid_generate_v4()),
  "client_id" int,
  "message" text NOT NULL,
  "message_type" text NOT NULL,
  "file_name" text NOT NULL,
  "language" text NOT NULL,
  "snippet" json NOT NULL,
  "line_number" int NOT NULL,
  "backtrace_id" int NOT NULL,
  "warnings" text[] NOT NULL,
  "date" timestamp NOT NULL DEFAULT (now()),
  "received_from" inet,
  PRIMARY KEY ("id", "client_id")
);

CREATE TABLE "Clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "last_connected" timestamp NOT NULL DEFAULT (now()),
  "logs_sent" int NOT NULL DEFAULT 0
);

ALTER TABLE "BacktracesLayers" ADD FOREIGN KEY ("backtrace_id") REFERENCES "Backtraces" ("id");

ALTER TABLE "BacktracesLayers" ADD FOREIGN KEY ("layer_id") REFERENCES "Layers" ("id");

ALTER TABLE "Logs" ADD FOREIGN KEY ("client_id") REFERENCES "Clients" ("id");

ALTER TABLE "Logs" ADD FOREIGN KEY ("backtrace_id") REFERENCES "Backtraces" ("id");
